// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: InternalCustomAlarm.proto
// Protobuf Java Version: 4.29.3

package dynamic.mapper.processor.extension.internal;

public final class InternalCustomAlarmOuter {
  private InternalCustomAlarmOuter() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 29,
      /* patch= */ 3,
      /* suffix= */ "",
      InternalCustomAlarmOuter.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface InternalCustomAlarmOrBuilder extends
      // @@protoc_insertion_point(interface_extends:processor.protobuf.InternalCustomAlarm)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int64 timestamp = 1;</code>
     * @return The timestamp.
     */
    long getTimestamp();

    /**
     * <code>string txt = 2;</code>
     * @return The txt.
     */
    java.lang.String getTxt();
    /**
     * <code>string txt = 2;</code>
     * @return The bytes for txt.
     */
    com.google.protobuf.ByteString
        getTxtBytes();

    /**
     * <code>string unit = 3;</code>
     * @return The unit.
     */
    java.lang.String getUnit();
    /**
     * <code>string unit = 3;</code>
     * @return The bytes for unit.
     */
    com.google.protobuf.ByteString
        getUnitBytes();

    /**
     * <code>string externalIdType = 4;</code>
     * @return The externalIdType.
     */
    java.lang.String getExternalIdType();
    /**
     * <code>string externalIdType = 4;</code>
     * @return The bytes for externalIdType.
     */
    com.google.protobuf.ByteString
        getExternalIdTypeBytes();

    /**
     * <code>string externalId = 5;</code>
     * @return The externalId.
     */
    java.lang.String getExternalId();
    /**
     * <code>string externalId = 5;</code>
     * @return The bytes for externalId.
     */
    com.google.protobuf.ByteString
        getExternalIdBytes();

    /**
     * <code>string alarmType = 6;</code>
     * @return The alarmType.
     */
    java.lang.String getAlarmType();
    /**
     * <code>string alarmType = 6;</code>
     * @return The bytes for alarmType.
     */
    com.google.protobuf.ByteString
        getAlarmTypeBytes();

    /**
     * <code>string severity = 7;</code>
     * @return The severity.
     */
    java.lang.String getSeverity();
    /**
     * <code>string severity = 7;</code>
     * @return The bytes for severity.
     */
    com.google.protobuf.ByteString
        getSeverityBytes();
  }
  /**
   * Protobuf type {@code processor.protobuf.InternalCustomAlarm}
   */
  public static final class InternalCustomAlarm extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:processor.protobuf.InternalCustomAlarm)
      InternalCustomAlarmOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 29,
        /* patch= */ 3,
        /* suffix= */ "",
        InternalCustomAlarm.class.getName());
    }
    // Use InternalCustomAlarm.newBuilder() to construct.
    private InternalCustomAlarm(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private InternalCustomAlarm() {
      txt_ = "";
      unit_ = "";
      externalIdType_ = "";
      externalId_ = "";
      alarmType_ = "";
      severity_ = "";
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return dynamic.mapper.processor.extension.internal.InternalCustomAlarmOuter.internal_static_processor_protobuf_InternalCustomAlarm_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return dynamic.mapper.processor.extension.internal.InternalCustomAlarmOuter.internal_static_processor_protobuf_InternalCustomAlarm_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              dynamic.mapper.processor.extension.internal.InternalCustomAlarmOuter.InternalCustomAlarm.class, dynamic.mapper.processor.extension.internal.InternalCustomAlarmOuter.InternalCustomAlarm.Builder.class);
    }

    public static final int TIMESTAMP_FIELD_NUMBER = 1;
    private long timestamp_ = 0L;
    /**
     * <code>int64 timestamp = 1;</code>
     * @return The timestamp.
     */
    @java.lang.Override
    public long getTimestamp() {
      return timestamp_;
    }

    public static final int TXT_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private volatile java.lang.Object txt_ = "";
    /**
     * <code>string txt = 2;</code>
     * @return The txt.
     */
    @java.lang.Override
    public java.lang.String getTxt() {
      java.lang.Object ref = txt_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        txt_ = s;
        return s;
      }
    }
    /**
     * <code>string txt = 2;</code>
     * @return The bytes for txt.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getTxtBytes() {
      java.lang.Object ref = txt_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        txt_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int UNIT_FIELD_NUMBER = 3;
    @SuppressWarnings("serial")
    private volatile java.lang.Object unit_ = "";
    /**
     * <code>string unit = 3;</code>
     * @return The unit.
     */
    @java.lang.Override
    public java.lang.String getUnit() {
      java.lang.Object ref = unit_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        unit_ = s;
        return s;
      }
    }
    /**
     * <code>string unit = 3;</code>
     * @return The bytes for unit.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getUnitBytes() {
      java.lang.Object ref = unit_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        unit_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int EXTERNALIDTYPE_FIELD_NUMBER = 4;
    @SuppressWarnings("serial")
    private volatile java.lang.Object externalIdType_ = "";
    /**
     * <code>string externalIdType = 4;</code>
     * @return The externalIdType.
     */
    @java.lang.Override
    public java.lang.String getExternalIdType() {
      java.lang.Object ref = externalIdType_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        externalIdType_ = s;
        return s;
      }
    }
    /**
     * <code>string externalIdType = 4;</code>
     * @return The bytes for externalIdType.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getExternalIdTypeBytes() {
      java.lang.Object ref = externalIdType_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        externalIdType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int EXTERNALID_FIELD_NUMBER = 5;
    @SuppressWarnings("serial")
    private volatile java.lang.Object externalId_ = "";
    /**
     * <code>string externalId = 5;</code>
     * @return The externalId.
     */
    @java.lang.Override
    public java.lang.String getExternalId() {
      java.lang.Object ref = externalId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        externalId_ = s;
        return s;
      }
    }
    /**
     * <code>string externalId = 5;</code>
     * @return The bytes for externalId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getExternalIdBytes() {
      java.lang.Object ref = externalId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        externalId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ALARMTYPE_FIELD_NUMBER = 6;
    @SuppressWarnings("serial")
    private volatile java.lang.Object alarmType_ = "";
    /**
     * <code>string alarmType = 6;</code>
     * @return The alarmType.
     */
    @java.lang.Override
    public java.lang.String getAlarmType() {
      java.lang.Object ref = alarmType_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        alarmType_ = s;
        return s;
      }
    }
    /**
     * <code>string alarmType = 6;</code>
     * @return The bytes for alarmType.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getAlarmTypeBytes() {
      java.lang.Object ref = alarmType_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        alarmType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SEVERITY_FIELD_NUMBER = 7;
    @SuppressWarnings("serial")
    private volatile java.lang.Object severity_ = "";
    /**
     * <code>string severity = 7;</code>
     * @return The severity.
     */
    @java.lang.Override
    public java.lang.String getSeverity() {
      java.lang.Object ref = severity_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        severity_ = s;
        return s;
      }
    }
    /**
     * <code>string severity = 7;</code>
     * @return The bytes for severity.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getSeverityBytes() {
      java.lang.Object ref = severity_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        severity_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (timestamp_ != 0L) {
        output.writeInt64(1, timestamp_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(txt_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 2, txt_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(unit_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 3, unit_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(externalIdType_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 4, externalIdType_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(externalId_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 5, externalId_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(alarmType_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 6, alarmType_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(severity_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 7, severity_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (timestamp_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, timestamp_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(txt_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(2, txt_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(unit_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(3, unit_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(externalIdType_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(4, externalIdType_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(externalId_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(5, externalId_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(alarmType_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(6, alarmType_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(severity_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(7, severity_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof dynamic.mapper.processor.extension.internal.InternalCustomAlarmOuter.InternalCustomAlarm)) {
        return super.equals(obj);
      }
      dynamic.mapper.processor.extension.internal.InternalCustomAlarmOuter.InternalCustomAlarm other = (dynamic.mapper.processor.extension.internal.InternalCustomAlarmOuter.InternalCustomAlarm) obj;

      if (getTimestamp()
          != other.getTimestamp()) return false;
      if (!getTxt()
          .equals(other.getTxt())) return false;
      if (!getUnit()
          .equals(other.getUnit())) return false;
      if (!getExternalIdType()
          .equals(other.getExternalIdType())) return false;
      if (!getExternalId()
          .equals(other.getExternalId())) return false;
      if (!getAlarmType()
          .equals(other.getAlarmType())) return false;
      if (!getSeverity()
          .equals(other.getSeverity())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getTimestamp());
      hash = (37 * hash) + TXT_FIELD_NUMBER;
      hash = (53 * hash) + getTxt().hashCode();
      hash = (37 * hash) + UNIT_FIELD_NUMBER;
      hash = (53 * hash) + getUnit().hashCode();
      hash = (37 * hash) + EXTERNALIDTYPE_FIELD_NUMBER;
      hash = (53 * hash) + getExternalIdType().hashCode();
      hash = (37 * hash) + EXTERNALID_FIELD_NUMBER;
      hash = (53 * hash) + getExternalId().hashCode();
      hash = (37 * hash) + ALARMTYPE_FIELD_NUMBER;
      hash = (53 * hash) + getAlarmType().hashCode();
      hash = (37 * hash) + SEVERITY_FIELD_NUMBER;
      hash = (53 * hash) + getSeverity().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static dynamic.mapper.processor.extension.internal.InternalCustomAlarmOuter.InternalCustomAlarm parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static dynamic.mapper.processor.extension.internal.InternalCustomAlarmOuter.InternalCustomAlarm parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static dynamic.mapper.processor.extension.internal.InternalCustomAlarmOuter.InternalCustomAlarm parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static dynamic.mapper.processor.extension.internal.InternalCustomAlarmOuter.InternalCustomAlarm parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static dynamic.mapper.processor.extension.internal.InternalCustomAlarmOuter.InternalCustomAlarm parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static dynamic.mapper.processor.extension.internal.InternalCustomAlarmOuter.InternalCustomAlarm parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static dynamic.mapper.processor.extension.internal.InternalCustomAlarmOuter.InternalCustomAlarm parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static dynamic.mapper.processor.extension.internal.InternalCustomAlarmOuter.InternalCustomAlarm parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static dynamic.mapper.processor.extension.internal.InternalCustomAlarmOuter.InternalCustomAlarm parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static dynamic.mapper.processor.extension.internal.InternalCustomAlarmOuter.InternalCustomAlarm parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static dynamic.mapper.processor.extension.internal.InternalCustomAlarmOuter.InternalCustomAlarm parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static dynamic.mapper.processor.extension.internal.InternalCustomAlarmOuter.InternalCustomAlarm parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(dynamic.mapper.processor.extension.internal.InternalCustomAlarmOuter.InternalCustomAlarm prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code processor.protobuf.InternalCustomAlarm}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:processor.protobuf.InternalCustomAlarm)
        dynamic.mapper.processor.extension.internal.InternalCustomAlarmOuter.InternalCustomAlarmOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return dynamic.mapper.processor.extension.internal.InternalCustomAlarmOuter.internal_static_processor_protobuf_InternalCustomAlarm_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return dynamic.mapper.processor.extension.internal.InternalCustomAlarmOuter.internal_static_processor_protobuf_InternalCustomAlarm_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                dynamic.mapper.processor.extension.internal.InternalCustomAlarmOuter.InternalCustomAlarm.class, dynamic.mapper.processor.extension.internal.InternalCustomAlarmOuter.InternalCustomAlarm.Builder.class);
      }

      // Construct using dynamic.mapper.processor.extension.internal.InternalCustomAlarmOuter.InternalCustomAlarm.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        timestamp_ = 0L;
        txt_ = "";
        unit_ = "";
        externalIdType_ = "";
        externalId_ = "";
        alarmType_ = "";
        severity_ = "";
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return dynamic.mapper.processor.extension.internal.InternalCustomAlarmOuter.internal_static_processor_protobuf_InternalCustomAlarm_descriptor;
      }

      @java.lang.Override
      public dynamic.mapper.processor.extension.internal.InternalCustomAlarmOuter.InternalCustomAlarm getDefaultInstanceForType() {
        return dynamic.mapper.processor.extension.internal.InternalCustomAlarmOuter.InternalCustomAlarm.getDefaultInstance();
      }

      @java.lang.Override
      public dynamic.mapper.processor.extension.internal.InternalCustomAlarmOuter.InternalCustomAlarm build() {
        dynamic.mapper.processor.extension.internal.InternalCustomAlarmOuter.InternalCustomAlarm result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public dynamic.mapper.processor.extension.internal.InternalCustomAlarmOuter.InternalCustomAlarm buildPartial() {
        dynamic.mapper.processor.extension.internal.InternalCustomAlarmOuter.InternalCustomAlarm result = new dynamic.mapper.processor.extension.internal.InternalCustomAlarmOuter.InternalCustomAlarm(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(dynamic.mapper.processor.extension.internal.InternalCustomAlarmOuter.InternalCustomAlarm result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.timestamp_ = timestamp_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.txt_ = txt_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.unit_ = unit_;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.externalIdType_ = externalIdType_;
        }
        if (((from_bitField0_ & 0x00000010) != 0)) {
          result.externalId_ = externalId_;
        }
        if (((from_bitField0_ & 0x00000020) != 0)) {
          result.alarmType_ = alarmType_;
        }
        if (((from_bitField0_ & 0x00000040) != 0)) {
          result.severity_ = severity_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof dynamic.mapper.processor.extension.internal.InternalCustomAlarmOuter.InternalCustomAlarm) {
          return mergeFrom((dynamic.mapper.processor.extension.internal.InternalCustomAlarmOuter.InternalCustomAlarm)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(dynamic.mapper.processor.extension.internal.InternalCustomAlarmOuter.InternalCustomAlarm other) {
        if (other == dynamic.mapper.processor.extension.internal.InternalCustomAlarmOuter.InternalCustomAlarm.getDefaultInstance()) return this;
        if (other.getTimestamp() != 0L) {
          setTimestamp(other.getTimestamp());
        }
        if (!other.getTxt().isEmpty()) {
          txt_ = other.txt_;
          bitField0_ |= 0x00000002;
          onChanged();
        }
        if (!other.getUnit().isEmpty()) {
          unit_ = other.unit_;
          bitField0_ |= 0x00000004;
          onChanged();
        }
        if (!other.getExternalIdType().isEmpty()) {
          externalIdType_ = other.externalIdType_;
          bitField0_ |= 0x00000008;
          onChanged();
        }
        if (!other.getExternalId().isEmpty()) {
          externalId_ = other.externalId_;
          bitField0_ |= 0x00000010;
          onChanged();
        }
        if (!other.getAlarmType().isEmpty()) {
          alarmType_ = other.alarmType_;
          bitField0_ |= 0x00000020;
          onChanged();
        }
        if (!other.getSeverity().isEmpty()) {
          severity_ = other.severity_;
          bitField0_ |= 0x00000040;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                timestamp_ = input.readInt64();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 18: {
                txt_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              case 26: {
                unit_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000004;
                break;
              } // case 26
              case 34: {
                externalIdType_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000008;
                break;
              } // case 34
              case 42: {
                externalId_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000010;
                break;
              } // case 42
              case 50: {
                alarmType_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000020;
                break;
              } // case 50
              case 58: {
                severity_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000040;
                break;
              } // case 58
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private long timestamp_ ;
      /**
       * <code>int64 timestamp = 1;</code>
       * @return The timestamp.
       */
      @java.lang.Override
      public long getTimestamp() {
        return timestamp_;
      }
      /**
       * <code>int64 timestamp = 1;</code>
       * @param value The timestamp to set.
       * @return This builder for chaining.
       */
      public Builder setTimestamp(long value) {

        timestamp_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>int64 timestamp = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearTimestamp() {
        bitField0_ = (bitField0_ & ~0x00000001);
        timestamp_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object txt_ = "";
      /**
       * <code>string txt = 2;</code>
       * @return The txt.
       */
      public java.lang.String getTxt() {
        java.lang.Object ref = txt_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          txt_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string txt = 2;</code>
       * @return The bytes for txt.
       */
      public com.google.protobuf.ByteString
          getTxtBytes() {
        java.lang.Object ref = txt_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          txt_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string txt = 2;</code>
       * @param value The txt to set.
       * @return This builder for chaining.
       */
      public Builder setTxt(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        txt_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>string txt = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearTxt() {
        txt_ = getDefaultInstance().getTxt();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>string txt = 2;</code>
       * @param value The bytes for txt to set.
       * @return This builder for chaining.
       */
      public Builder setTxtBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        txt_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }

      private java.lang.Object unit_ = "";
      /**
       * <code>string unit = 3;</code>
       * @return The unit.
       */
      public java.lang.String getUnit() {
        java.lang.Object ref = unit_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          unit_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string unit = 3;</code>
       * @return The bytes for unit.
       */
      public com.google.protobuf.ByteString
          getUnitBytes() {
        java.lang.Object ref = unit_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          unit_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string unit = 3;</code>
       * @param value The unit to set.
       * @return This builder for chaining.
       */
      public Builder setUnit(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        unit_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>string unit = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearUnit() {
        unit_ = getDefaultInstance().getUnit();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }
      /**
       * <code>string unit = 3;</code>
       * @param value The bytes for unit to set.
       * @return This builder for chaining.
       */
      public Builder setUnitBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        unit_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }

      private java.lang.Object externalIdType_ = "";
      /**
       * <code>string externalIdType = 4;</code>
       * @return The externalIdType.
       */
      public java.lang.String getExternalIdType() {
        java.lang.Object ref = externalIdType_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          externalIdType_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string externalIdType = 4;</code>
       * @return The bytes for externalIdType.
       */
      public com.google.protobuf.ByteString
          getExternalIdTypeBytes() {
        java.lang.Object ref = externalIdType_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          externalIdType_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string externalIdType = 4;</code>
       * @param value The externalIdType to set.
       * @return This builder for chaining.
       */
      public Builder setExternalIdType(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        externalIdType_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>string externalIdType = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearExternalIdType() {
        externalIdType_ = getDefaultInstance().getExternalIdType();
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
        return this;
      }
      /**
       * <code>string externalIdType = 4;</code>
       * @param value The bytes for externalIdType to set.
       * @return This builder for chaining.
       */
      public Builder setExternalIdTypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        externalIdType_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }

      private java.lang.Object externalId_ = "";
      /**
       * <code>string externalId = 5;</code>
       * @return The externalId.
       */
      public java.lang.String getExternalId() {
        java.lang.Object ref = externalId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          externalId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string externalId = 5;</code>
       * @return The bytes for externalId.
       */
      public com.google.protobuf.ByteString
          getExternalIdBytes() {
        java.lang.Object ref = externalId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          externalId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string externalId = 5;</code>
       * @param value The externalId to set.
       * @return This builder for chaining.
       */
      public Builder setExternalId(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        externalId_ = value;
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      /**
       * <code>string externalId = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearExternalId() {
        externalId_ = getDefaultInstance().getExternalId();
        bitField0_ = (bitField0_ & ~0x00000010);
        onChanged();
        return this;
      }
      /**
       * <code>string externalId = 5;</code>
       * @param value The bytes for externalId to set.
       * @return This builder for chaining.
       */
      public Builder setExternalIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        externalId_ = value;
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }

      private java.lang.Object alarmType_ = "";
      /**
       * <code>string alarmType = 6;</code>
       * @return The alarmType.
       */
      public java.lang.String getAlarmType() {
        java.lang.Object ref = alarmType_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          alarmType_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string alarmType = 6;</code>
       * @return The bytes for alarmType.
       */
      public com.google.protobuf.ByteString
          getAlarmTypeBytes() {
        java.lang.Object ref = alarmType_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          alarmType_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string alarmType = 6;</code>
       * @param value The alarmType to set.
       * @return This builder for chaining.
       */
      public Builder setAlarmType(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        alarmType_ = value;
        bitField0_ |= 0x00000020;
        onChanged();
        return this;
      }
      /**
       * <code>string alarmType = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearAlarmType() {
        alarmType_ = getDefaultInstance().getAlarmType();
        bitField0_ = (bitField0_ & ~0x00000020);
        onChanged();
        return this;
      }
      /**
       * <code>string alarmType = 6;</code>
       * @param value The bytes for alarmType to set.
       * @return This builder for chaining.
       */
      public Builder setAlarmTypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        alarmType_ = value;
        bitField0_ |= 0x00000020;
        onChanged();
        return this;
      }

      private java.lang.Object severity_ = "";
      /**
       * <code>string severity = 7;</code>
       * @return The severity.
       */
      public java.lang.String getSeverity() {
        java.lang.Object ref = severity_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          severity_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string severity = 7;</code>
       * @return The bytes for severity.
       */
      public com.google.protobuf.ByteString
          getSeverityBytes() {
        java.lang.Object ref = severity_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          severity_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string severity = 7;</code>
       * @param value The severity to set.
       * @return This builder for chaining.
       */
      public Builder setSeverity(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        severity_ = value;
        bitField0_ |= 0x00000040;
        onChanged();
        return this;
      }
      /**
       * <code>string severity = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearSeverity() {
        severity_ = getDefaultInstance().getSeverity();
        bitField0_ = (bitField0_ & ~0x00000040);
        onChanged();
        return this;
      }
      /**
       * <code>string severity = 7;</code>
       * @param value The bytes for severity to set.
       * @return This builder for chaining.
       */
      public Builder setSeverityBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        severity_ = value;
        bitField0_ |= 0x00000040;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:processor.protobuf.InternalCustomAlarm)
    }

    // @@protoc_insertion_point(class_scope:processor.protobuf.InternalCustomAlarm)
    private static final dynamic.mapper.processor.extension.internal.InternalCustomAlarmOuter.InternalCustomAlarm DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new dynamic.mapper.processor.extension.internal.InternalCustomAlarmOuter.InternalCustomAlarm();
    }

    public static dynamic.mapper.processor.extension.internal.InternalCustomAlarmOuter.InternalCustomAlarm getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<InternalCustomAlarm>
        PARSER = new com.google.protobuf.AbstractParser<InternalCustomAlarm>() {
      @java.lang.Override
      public InternalCustomAlarm parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<InternalCustomAlarm> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<InternalCustomAlarm> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public dynamic.mapper.processor.extension.internal.InternalCustomAlarmOuter.InternalCustomAlarm getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_processor_protobuf_InternalCustomAlarm_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_processor_protobuf_InternalCustomAlarm_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\031InternalCustomAlarm.proto\022\022processor.p" +
      "rotobuf\"\224\001\n\023InternalCustomAlarm\022\021\n\ttimes" +
      "tamp\030\001 \001(\003\022\013\n\003txt\030\002 \001(\t\022\014\n\004unit\030\003 \001(\t\022\026\n" +
      "\016externalIdType\030\004 \001(\t\022\022\n\nexternalId\030\005 \001(" +
      "\t\022\021\n\talarmType\030\006 \001(\t\022\020\n\010severity\030\007 \001(\tBG" +
      "\n+dynamic.mapper.processor.extension.int" +
      "ernalB\030InternalCustomAlarmOuterb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_processor_protobuf_InternalCustomAlarm_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_processor_protobuf_InternalCustomAlarm_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_processor_protobuf_InternalCustomAlarm_descriptor,
        new java.lang.String[] { "Timestamp", "Txt", "Unit", "ExternalIdType", "ExternalId", "AlarmType", "Severity", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
