// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: InternalCustomMeasurement.proto
// Protobuf Java Version: 4.29.3

package dynamic.mapper.processor.processor.fixed;

import com.google.protobuf.AbstractParser;
import com.google.protobuf.ByteString;
import com.google.protobuf.CodedInputStream;
import com.google.protobuf.CodedOutputStream;
import com.google.protobuf.Descriptors;
import com.google.protobuf.ExtensionRegistry;
import com.google.protobuf.ExtensionRegistryLite;
import com.google.protobuf.GeneratedMessage;
import com.google.protobuf.Internal;
import com.google.protobuf.InvalidProtocolBufferException;
import com.google.protobuf.Message;
import com.google.protobuf.MessageOrBuilder;
import com.google.protobuf.Parser;
import com.google.protobuf.RuntimeVersion;
import com.google.protobuf.UninitializedMessageException;
import java.io.IOException;
import java.io.InputStream;
import java.nio.ByteBuffer;

public final class InternalCustomMeasurementOuter {
  private InternalCustomMeasurementOuter() {}
  static {
    RuntimeVersion.validateProtobufGencodeVersion(
      RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 29,
      /* patch= */ 3,
      /* suffix= */ "",
      InternalCustomMeasurementOuter.class.getName());
  }
  public static void registerAllExtensions(
      ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      ExtensionRegistry registry) {
    registerAllExtensions(
        (ExtensionRegistryLite) registry);
  }
  public interface InternalCustomMeasurementOrBuilder extends
      // @@protoc_insertion_point(interface_extends:processor.protobuf.InternalCustomMeasurement)
      MessageOrBuilder {

    /**
     * <code>int64 timestamp = 1;</code>
     * @return The timestamp.
     */
    long getTimestamp();

    /**
     * <code>float value = 2;</code>
     * @return The value.
     */
    float getValue();

    /**
     * <code>string unit = 3;</code>
     * @return The unit.
     */
    String getUnit();
    /**
     * <code>string unit = 3;</code>
     * @return The bytes for unit.
     */
    ByteString
        getUnitBytes();

    /**
     * <code>string externalIdType = 4;</code>
     * @return The externalIdType.
     */
    String getExternalIdType();
    /**
     * <code>string externalIdType = 4;</code>
     * @return The bytes for externalIdType.
     */
    ByteString
        getExternalIdTypeBytes();

    /**
     * <code>string externalId = 5;</code>
     * @return The externalId.
     */
    String getExternalId();
    /**
     * <code>string externalId = 5;</code>
     * @return The bytes for externalId.
     */
    ByteString
        getExternalIdBytes();

    /**
     * <code>string measurementType = 6;</code>
     * @return The measurementType.
     */
    String getMeasurementType();
    /**
     * <code>string measurementType = 6;</code>
     * @return The bytes for measurementType.
     */
    ByteString
        getMeasurementTypeBytes();
  }
  /**
   * Protobuf type {@code processor.protobuf.InternalCustomMeasurement}
   */
  public static final class InternalCustomMeasurement extends
      GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:processor.protobuf.InternalCustomMeasurement)
      InternalCustomMeasurementOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      RuntimeVersion.validateProtobufGencodeVersion(
        RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 29,
        /* patch= */ 3,
        /* suffix= */ "",
        InternalCustomMeasurement.class.getName());
    }
    // Use InternalCustomMeasurement.newBuilder() to construct.
    private InternalCustomMeasurement(GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private InternalCustomMeasurement() {
      unit_ = "";
      externalIdType_ = "";
      externalId_ = "";
      measurementType_ = "";
    }

    public static final Descriptors.Descriptor
        getDescriptor() {
      return dynamic.mapper.processor.processor.fixed.InternalCustomMeasurementOuter.internal_static_processor_protobuf_InternalCustomMeasurement_descriptor;
    }

    @Override
    protected GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return dynamic.mapper.processor.processor.fixed.InternalCustomMeasurementOuter.internal_static_processor_protobuf_InternalCustomMeasurement_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              dynamic.mapper.processor.processor.fixed.InternalCustomMeasurementOuter.InternalCustomMeasurement.class, dynamic.mapper.processor.processor.fixed.InternalCustomMeasurementOuter.InternalCustomMeasurement.Builder.class);
    }

    public static final int TIMESTAMP_FIELD_NUMBER = 1;
    private long timestamp_ = 0L;
    /**
     * <code>int64 timestamp = 1;</code>
     * @return The timestamp.
     */
    @Override
    public long getTimestamp() {
      return timestamp_;
    }

    public static final int VALUE_FIELD_NUMBER = 2;
    private float value_ = 0F;
    /**
     * <code>float value = 2;</code>
     * @return The value.
     */
    @Override
    public float getValue() {
      return value_;
    }

    public static final int UNIT_FIELD_NUMBER = 3;
    @SuppressWarnings("serial")
    private volatile Object unit_ = "";
    /**
     * <code>string unit = 3;</code>
     * @return The unit.
     */
    @Override
    public String getUnit() {
      Object ref = unit_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        ByteString bs = 
            (ByteString) ref;
        String s = bs.toStringUtf8();
        unit_ = s;
        return s;
      }
    }
    /**
     * <code>string unit = 3;</code>
     * @return The bytes for unit.
     */
    @Override
    public ByteString
        getUnitBytes() {
      Object ref = unit_;
      if (ref instanceof String) {
        ByteString b = 
            ByteString.copyFromUtf8(
                (String) ref);
        unit_ = b;
        return b;
      } else {
        return (ByteString) ref;
      }
    }

    public static final int EXTERNALIDTYPE_FIELD_NUMBER = 4;
    @SuppressWarnings("serial")
    private volatile Object externalIdType_ = "";
    /**
     * <code>string externalIdType = 4;</code>
     * @return The externalIdType.
     */
    @Override
    public String getExternalIdType() {
      Object ref = externalIdType_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        ByteString bs = 
            (ByteString) ref;
        String s = bs.toStringUtf8();
        externalIdType_ = s;
        return s;
      }
    }
    /**
     * <code>string externalIdType = 4;</code>
     * @return The bytes for externalIdType.
     */
    @Override
    public ByteString
        getExternalIdTypeBytes() {
      Object ref = externalIdType_;
      if (ref instanceof String) {
        ByteString b = 
            ByteString.copyFromUtf8(
                (String) ref);
        externalIdType_ = b;
        return b;
      } else {
        return (ByteString) ref;
      }
    }

    public static final int EXTERNALID_FIELD_NUMBER = 5;
    @SuppressWarnings("serial")
    private volatile Object externalId_ = "";
    /**
     * <code>string externalId = 5;</code>
     * @return The externalId.
     */
    @Override
    public String getExternalId() {
      Object ref = externalId_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        ByteString bs = 
            (ByteString) ref;
        String s = bs.toStringUtf8();
        externalId_ = s;
        return s;
      }
    }
    /**
     * <code>string externalId = 5;</code>
     * @return The bytes for externalId.
     */
    @Override
    public ByteString
        getExternalIdBytes() {
      Object ref = externalId_;
      if (ref instanceof String) {
        ByteString b = 
            ByteString.copyFromUtf8(
                (String) ref);
        externalId_ = b;
        return b;
      } else {
        return (ByteString) ref;
      }
    }

    public static final int MEASUREMENTTYPE_FIELD_NUMBER = 6;
    @SuppressWarnings("serial")
    private volatile Object measurementType_ = "";
    /**
     * <code>string measurementType = 6;</code>
     * @return The measurementType.
     */
    @Override
    public String getMeasurementType() {
      Object ref = measurementType_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        ByteString bs = 
            (ByteString) ref;
        String s = bs.toStringUtf8();
        measurementType_ = s;
        return s;
      }
    }
    /**
     * <code>string measurementType = 6;</code>
     * @return The bytes for measurementType.
     */
    @Override
    public ByteString
        getMeasurementTypeBytes() {
      Object ref = measurementType_;
      if (ref instanceof String) {
        ByteString b = 
            ByteString.copyFromUtf8(
                (String) ref);
        measurementType_ = b;
        return b;
      } else {
        return (ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(CodedOutputStream output)
                        throws IOException {
      if (timestamp_ != 0L) {
        output.writeInt64(1, timestamp_);
      }
      if (Float.floatToRawIntBits(value_) != 0) {
        output.writeFloat(2, value_);
      }
      if (!GeneratedMessage.isStringEmpty(unit_)) {
        GeneratedMessage.writeString(output, 3, unit_);
      }
      if (!GeneratedMessage.isStringEmpty(externalIdType_)) {
        GeneratedMessage.writeString(output, 4, externalIdType_);
      }
      if (!GeneratedMessage.isStringEmpty(externalId_)) {
        GeneratedMessage.writeString(output, 5, externalId_);
      }
      if (!GeneratedMessage.isStringEmpty(measurementType_)) {
        GeneratedMessage.writeString(output, 6, measurementType_);
      }
      getUnknownFields().writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (timestamp_ != 0L) {
        size += CodedOutputStream
          .computeInt64Size(1, timestamp_);
      }
      if (Float.floatToRawIntBits(value_) != 0) {
        size += CodedOutputStream
          .computeFloatSize(2, value_);
      }
      if (!GeneratedMessage.isStringEmpty(unit_)) {
        size += GeneratedMessage.computeStringSize(3, unit_);
      }
      if (!GeneratedMessage.isStringEmpty(externalIdType_)) {
        size += GeneratedMessage.computeStringSize(4, externalIdType_);
      }
      if (!GeneratedMessage.isStringEmpty(externalId_)) {
        size += GeneratedMessage.computeStringSize(5, externalId_);
      }
      if (!GeneratedMessage.isStringEmpty(measurementType_)) {
        size += GeneratedMessage.computeStringSize(6, measurementType_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof dynamic.mapper.processor.processor.fixed.InternalCustomMeasurementOuter.InternalCustomMeasurement)) {
        return super.equals(obj);
      }
      dynamic.mapper.processor.processor.fixed.InternalCustomMeasurementOuter.InternalCustomMeasurement other = (dynamic.mapper.processor.processor.fixed.InternalCustomMeasurementOuter.InternalCustomMeasurement) obj;

      if (getTimestamp()
          != other.getTimestamp()) return false;
      if (Float.floatToIntBits(getValue())
          != Float.floatToIntBits(
              other.getValue())) return false;
      if (!getUnit()
          .equals(other.getUnit())) return false;
      if (!getExternalIdType()
          .equals(other.getExternalIdType())) return false;
      if (!getExternalId()
          .equals(other.getExternalId())) return false;
      if (!getMeasurementType()
          .equals(other.getMeasurementType())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
      hash = (53 * hash) + Internal.hashLong(
          getTimestamp());
      hash = (37 * hash) + VALUE_FIELD_NUMBER;
      hash = (53 * hash) + Float.floatToIntBits(
          getValue());
      hash = (37 * hash) + UNIT_FIELD_NUMBER;
      hash = (53 * hash) + getUnit().hashCode();
      hash = (37 * hash) + EXTERNALIDTYPE_FIELD_NUMBER;
      hash = (53 * hash) + getExternalIdType().hashCode();
      hash = (37 * hash) + EXTERNALID_FIELD_NUMBER;
      hash = (53 * hash) + getExternalId().hashCode();
      hash = (37 * hash) + MEASUREMENTTYPE_FIELD_NUMBER;
      hash = (53 * hash) + getMeasurementType().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static dynamic.mapper.processor.processor.fixed.InternalCustomMeasurementOuter.InternalCustomMeasurement parseFrom(
        ByteBuffer data)
        throws InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static dynamic.mapper.processor.processor.fixed.InternalCustomMeasurementOuter.InternalCustomMeasurement parseFrom(
        ByteBuffer data,
        ExtensionRegistryLite extensionRegistry)
        throws InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static dynamic.mapper.processor.processor.fixed.InternalCustomMeasurementOuter.InternalCustomMeasurement parseFrom(
        ByteString data)
        throws InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static dynamic.mapper.processor.processor.fixed.InternalCustomMeasurementOuter.InternalCustomMeasurement parseFrom(
        ByteString data,
        ExtensionRegistryLite extensionRegistry)
        throws InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static dynamic.mapper.processor.processor.fixed.InternalCustomMeasurementOuter.InternalCustomMeasurement parseFrom(byte[] data)
        throws InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static dynamic.mapper.processor.processor.fixed.InternalCustomMeasurementOuter.InternalCustomMeasurement parseFrom(
        byte[] data,
        ExtensionRegistryLite extensionRegistry)
        throws InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static dynamic.mapper.processor.processor.fixed.InternalCustomMeasurementOuter.InternalCustomMeasurement parseFrom(InputStream input)
        throws IOException {
      return GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static dynamic.mapper.processor.processor.fixed.InternalCustomMeasurementOuter.InternalCustomMeasurement parseFrom(
        InputStream input,
        ExtensionRegistryLite extensionRegistry)
        throws IOException {
      return GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static dynamic.mapper.processor.processor.fixed.InternalCustomMeasurementOuter.InternalCustomMeasurement parseDelimitedFrom(InputStream input)
        throws IOException {
      return GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static dynamic.mapper.processor.processor.fixed.InternalCustomMeasurementOuter.InternalCustomMeasurement parseDelimitedFrom(
        InputStream input,
        ExtensionRegistryLite extensionRegistry)
        throws IOException {
      return GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static dynamic.mapper.processor.processor.fixed.InternalCustomMeasurementOuter.InternalCustomMeasurement parseFrom(
        CodedInputStream input)
        throws IOException {
      return GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static dynamic.mapper.processor.processor.fixed.InternalCustomMeasurementOuter.InternalCustomMeasurement parseFrom(
        CodedInputStream input,
        ExtensionRegistryLite extensionRegistry)
        throws IOException {
      return GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(dynamic.mapper.processor.processor.fixed.InternalCustomMeasurementOuter.InternalCustomMeasurement prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code processor.protobuf.InternalCustomMeasurement}
     */
    public static final class Builder extends
        GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:processor.protobuf.InternalCustomMeasurement)
        dynamic.mapper.processor.processor.fixed.InternalCustomMeasurementOuter.InternalCustomMeasurementOrBuilder {
      public static final Descriptors.Descriptor
          getDescriptor() {
        return dynamic.mapper.processor.processor.fixed.InternalCustomMeasurementOuter.internal_static_processor_protobuf_InternalCustomMeasurement_descriptor;
      }

      @Override
      protected GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return dynamic.mapper.processor.processor.fixed.InternalCustomMeasurementOuter.internal_static_processor_protobuf_InternalCustomMeasurement_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                dynamic.mapper.processor.processor.fixed.InternalCustomMeasurementOuter.InternalCustomMeasurement.class, dynamic.mapper.processor.processor.fixed.InternalCustomMeasurementOuter.InternalCustomMeasurement.Builder.class);
      }

      // Construct using dynamic.mapper.processor.processor.fixed.InternalCustomMeasurementOuter.InternalCustomMeasurement.newBuilder()
      private Builder() {

      }

      private Builder(
          GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        timestamp_ = 0L;
        value_ = 0F;
        unit_ = "";
        externalIdType_ = "";
        externalId_ = "";
        measurementType_ = "";
        return this;
      }

      @Override
      public Descriptors.Descriptor
          getDescriptorForType() {
        return dynamic.mapper.processor.processor.fixed.InternalCustomMeasurementOuter.internal_static_processor_protobuf_InternalCustomMeasurement_descriptor;
      }

      @Override
      public dynamic.mapper.processor.processor.fixed.InternalCustomMeasurementOuter.InternalCustomMeasurement getDefaultInstanceForType() {
        return dynamic.mapper.processor.processor.fixed.InternalCustomMeasurementOuter.InternalCustomMeasurement.getDefaultInstance();
      }

      @Override
      public dynamic.mapper.processor.processor.fixed.InternalCustomMeasurementOuter.InternalCustomMeasurement build() {
        dynamic.mapper.processor.processor.fixed.InternalCustomMeasurementOuter.InternalCustomMeasurement result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public dynamic.mapper.processor.processor.fixed.InternalCustomMeasurementOuter.InternalCustomMeasurement buildPartial() {
        dynamic.mapper.processor.processor.fixed.InternalCustomMeasurementOuter.InternalCustomMeasurement result = new dynamic.mapper.processor.processor.fixed.InternalCustomMeasurementOuter.InternalCustomMeasurement(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(dynamic.mapper.processor.processor.fixed.InternalCustomMeasurementOuter.InternalCustomMeasurement result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.timestamp_ = timestamp_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.value_ = value_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.unit_ = unit_;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.externalIdType_ = externalIdType_;
        }
        if (((from_bitField0_ & 0x00000010) != 0)) {
          result.externalId_ = externalId_;
        }
        if (((from_bitField0_ & 0x00000020) != 0)) {
          result.measurementType_ = measurementType_;
        }
      }

      @Override
      public Builder mergeFrom(Message other) {
        if (other instanceof dynamic.mapper.processor.processor.fixed.InternalCustomMeasurementOuter.InternalCustomMeasurement) {
          return mergeFrom((dynamic.mapper.processor.processor.fixed.InternalCustomMeasurementOuter.InternalCustomMeasurement)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(dynamic.mapper.processor.processor.fixed.InternalCustomMeasurementOuter.InternalCustomMeasurement other) {
        if (other == dynamic.mapper.processor.processor.fixed.InternalCustomMeasurementOuter.InternalCustomMeasurement.getDefaultInstance()) return this;
        if (other.getTimestamp() != 0L) {
          setTimestamp(other.getTimestamp());
        }
        if (other.getValue() != 0F) {
          setValue(other.getValue());
        }
        if (!other.getUnit().isEmpty()) {
          unit_ = other.unit_;
          bitField0_ |= 0x00000004;
          onChanged();
        }
        if (!other.getExternalIdType().isEmpty()) {
          externalIdType_ = other.externalIdType_;
          bitField0_ |= 0x00000008;
          onChanged();
        }
        if (!other.getExternalId().isEmpty()) {
          externalId_ = other.externalId_;
          bitField0_ |= 0x00000010;
          onChanged();
        }
        if (!other.getMeasurementType().isEmpty()) {
          measurementType_ = other.measurementType_;
          bitField0_ |= 0x00000020;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          CodedInputStream input,
          ExtensionRegistryLite extensionRegistry)
          throws IOException {
        if (extensionRegistry == null) {
          throw new NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                timestamp_ = input.readInt64();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 21: {
                value_ = input.readFloat();
                bitField0_ |= 0x00000002;
                break;
              } // case 21
              case 26: {
                unit_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000004;
                break;
              } // case 26
              case 34: {
                externalIdType_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000008;
                break;
              } // case 34
              case 42: {
                externalId_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000010;
                break;
              } // case 42
              case 50: {
                measurementType_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000020;
                break;
              } // case 50
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private long timestamp_ ;
      /**
       * <code>int64 timestamp = 1;</code>
       * @return The timestamp.
       */
      @Override
      public long getTimestamp() {
        return timestamp_;
      }
      /**
       * <code>int64 timestamp = 1;</code>
       * @param value The timestamp to set.
       * @return This builder for chaining.
       */
      public Builder setTimestamp(long value) {

        timestamp_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>int64 timestamp = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearTimestamp() {
        bitField0_ = (bitField0_ & ~0x00000001);
        timestamp_ = 0L;
        onChanged();
        return this;
      }

      private float value_ ;
      /**
       * <code>float value = 2;</code>
       * @return The value.
       */
      @Override
      public float getValue() {
        return value_;
      }
      /**
       * <code>float value = 2;</code>
       * @param value The value to set.
       * @return This builder for chaining.
       */
      public Builder setValue(float value) {

        value_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>float value = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearValue() {
        bitField0_ = (bitField0_ & ~0x00000002);
        value_ = 0F;
        onChanged();
        return this;
      }

      private Object unit_ = "";
      /**
       * <code>string unit = 3;</code>
       * @return The unit.
       */
      public String getUnit() {
        Object ref = unit_;
        if (!(ref instanceof String)) {
          ByteString bs =
              (ByteString) ref;
          String s = bs.toStringUtf8();
          unit_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string unit = 3;</code>
       * @return The bytes for unit.
       */
      public ByteString
          getUnitBytes() {
        Object ref = unit_;
        if (ref instanceof String) {
          ByteString b = 
              ByteString.copyFromUtf8(
                  (String) ref);
          unit_ = b;
          return b;
        } else {
          return (ByteString) ref;
        }
      }
      /**
       * <code>string unit = 3;</code>
       * @param value The unit to set.
       * @return This builder for chaining.
       */
      public Builder setUnit(
          String value) {
        if (value == null) { throw new NullPointerException(); }
        unit_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>string unit = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearUnit() {
        unit_ = getDefaultInstance().getUnit();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }
      /**
       * <code>string unit = 3;</code>
       * @param value The bytes for unit to set.
       * @return This builder for chaining.
       */
      public Builder setUnitBytes(
          ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        unit_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }

      private Object externalIdType_ = "";
      /**
       * <code>string externalIdType = 4;</code>
       * @return The externalIdType.
       */
      public String getExternalIdType() {
        Object ref = externalIdType_;
        if (!(ref instanceof String)) {
          ByteString bs =
              (ByteString) ref;
          String s = bs.toStringUtf8();
          externalIdType_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string externalIdType = 4;</code>
       * @return The bytes for externalIdType.
       */
      public ByteString
          getExternalIdTypeBytes() {
        Object ref = externalIdType_;
        if (ref instanceof String) {
          ByteString b = 
              ByteString.copyFromUtf8(
                  (String) ref);
          externalIdType_ = b;
          return b;
        } else {
          return (ByteString) ref;
        }
      }
      /**
       * <code>string externalIdType = 4;</code>
       * @param value The externalIdType to set.
       * @return This builder for chaining.
       */
      public Builder setExternalIdType(
          String value) {
        if (value == null) { throw new NullPointerException(); }
        externalIdType_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>string externalIdType = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearExternalIdType() {
        externalIdType_ = getDefaultInstance().getExternalIdType();
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
        return this;
      }
      /**
       * <code>string externalIdType = 4;</code>
       * @param value The bytes for externalIdType to set.
       * @return This builder for chaining.
       */
      public Builder setExternalIdTypeBytes(
          ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        externalIdType_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }

      private Object externalId_ = "";
      /**
       * <code>string externalId = 5;</code>
       * @return The externalId.
       */
      public String getExternalId() {
        Object ref = externalId_;
        if (!(ref instanceof String)) {
          ByteString bs =
              (ByteString) ref;
          String s = bs.toStringUtf8();
          externalId_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string externalId = 5;</code>
       * @return The bytes for externalId.
       */
      public ByteString
          getExternalIdBytes() {
        Object ref = externalId_;
        if (ref instanceof String) {
          ByteString b = 
              ByteString.copyFromUtf8(
                  (String) ref);
          externalId_ = b;
          return b;
        } else {
          return (ByteString) ref;
        }
      }
      /**
       * <code>string externalId = 5;</code>
       * @param value The externalId to set.
       * @return This builder for chaining.
       */
      public Builder setExternalId(
          String value) {
        if (value == null) { throw new NullPointerException(); }
        externalId_ = value;
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      /**
       * <code>string externalId = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearExternalId() {
        externalId_ = getDefaultInstance().getExternalId();
        bitField0_ = (bitField0_ & ~0x00000010);
        onChanged();
        return this;
      }
      /**
       * <code>string externalId = 5;</code>
       * @param value The bytes for externalId to set.
       * @return This builder for chaining.
       */
      public Builder setExternalIdBytes(
          ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        externalId_ = value;
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }

      private Object measurementType_ = "";
      /**
       * <code>string measurementType = 6;</code>
       * @return The measurementType.
       */
      public String getMeasurementType() {
        Object ref = measurementType_;
        if (!(ref instanceof String)) {
          ByteString bs =
              (ByteString) ref;
          String s = bs.toStringUtf8();
          measurementType_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string measurementType = 6;</code>
       * @return The bytes for measurementType.
       */
      public ByteString
          getMeasurementTypeBytes() {
        Object ref = measurementType_;
        if (ref instanceof String) {
          ByteString b = 
              ByteString.copyFromUtf8(
                  (String) ref);
          measurementType_ = b;
          return b;
        } else {
          return (ByteString) ref;
        }
      }
      /**
       * <code>string measurementType = 6;</code>
       * @param value The measurementType to set.
       * @return This builder for chaining.
       */
      public Builder setMeasurementType(
          String value) {
        if (value == null) { throw new NullPointerException(); }
        measurementType_ = value;
        bitField0_ |= 0x00000020;
        onChanged();
        return this;
      }
      /**
       * <code>string measurementType = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearMeasurementType() {
        measurementType_ = getDefaultInstance().getMeasurementType();
        bitField0_ = (bitField0_ & ~0x00000020);
        onChanged();
        return this;
      }
      /**
       * <code>string measurementType = 6;</code>
       * @param value The bytes for measurementType to set.
       * @return This builder for chaining.
       */
      public Builder setMeasurementTypeBytes(
          ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        measurementType_ = value;
        bitField0_ |= 0x00000020;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:processor.protobuf.InternalCustomMeasurement)
    }

    // @@protoc_insertion_point(class_scope:processor.protobuf.InternalCustomMeasurement)
    private static final dynamic.mapper.processor.processor.fixed.InternalCustomMeasurementOuter.InternalCustomMeasurement DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new dynamic.mapper.processor.processor.fixed.InternalCustomMeasurementOuter.InternalCustomMeasurement();
    }

    public static dynamic.mapper.processor.processor.fixed.InternalCustomMeasurementOuter.InternalCustomMeasurement getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final Parser<InternalCustomMeasurement>
        PARSER = new AbstractParser<InternalCustomMeasurement>() {
      @Override
      public InternalCustomMeasurement parsePartialFrom(
          CodedInputStream input,
          ExtensionRegistryLite extensionRegistry)
          throws InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (IOException e) {
          throw new InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static Parser<InternalCustomMeasurement> parser() {
      return PARSER;
    }

    @Override
    public Parser<InternalCustomMeasurement> getParserForType() {
      return PARSER;
    }

    @Override
    public dynamic.mapper.processor.processor.fixed.InternalCustomMeasurementOuter.InternalCustomMeasurement getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final Descriptors.Descriptor
    internal_static_processor_protobuf_InternalCustomMeasurement_descriptor;
  private static final 
    GeneratedMessage.FieldAccessorTable
      internal_static_processor_protobuf_InternalCustomMeasurement_fieldAccessorTable;

  public static Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\037InternalCustomMeasurement.proto\022\022proce" +
      "ssor.protobuf\"\220\001\n\031InternalCustomMeasurem" +
      "ent\022\021\n\ttimestamp\030\001 \001(\003\022\r\n\005value\030\002 \001(\002\022\014\n" +
      "\004unit\030\003 \001(\t\022\026\n\016externalIdType\030\004 \001(\t\022\022\n\ne" +
      "xternalId\030\005 \001(\t\022\027\n\017measurementType\030\006 \001(\t" +
      "BJ\n(dynamic.mapper.processor.processor.f" +
      "ixedB\036InternalCustomMeasurementOuterb\006pr" +
      "oto3"
    };
    descriptor = Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new Descriptors.FileDescriptor[] {
        });
    internal_static_processor_protobuf_InternalCustomMeasurement_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_processor_protobuf_InternalCustomMeasurement_fieldAccessorTable = new
      GeneratedMessage.FieldAccessorTable(
        internal_static_processor_protobuf_InternalCustomMeasurement_descriptor,
        new String[] { "Timestamp", "Value", "Unit", "ExternalIdType", "ExternalId", "MeasurementType", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
