/*
 * Copyright (c) 2022-2025 Cumulocity GmbH.
 *
 * SPDX-License-Identifier: Apache-2.0
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *       http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 *
 *  @authors Christof Strack, Stefan Witschel
 *
 */
package dynamic.mapper.processor.model;

/**
 * Input message wrapper passed to SMART_FUNCTION JavaScript code as the first argument ({@code msg}).
 *
 * <p>Intentionally avoids Lombok so that GraalVM's {@code allowPublicAccess(true)} can reliably
 * discover and expose the public getter methods to JavaScript. Lombok-generated bytecode is not
 * consistently visible through GraalVM's host-access reflection.</p>
 *
 * <p>JavaScript usage:</p>
 * <pre>
 *   function onMessage(msg, context) {
 *       var payload = msg.getPayload();   // the parsed message payload (Map or String)
 *       var topic   = msg.getTopic();     // broker topic
 *       var client  = msg.getClientId();  // inbound: MQTT client id; outbound: null
 *       var source  = msg.getSourceId();  // outbound: C8Y device id; inbound: null
 *   }
 * </pre>
 */
public class InputMessage {

    private final Object payload;
    private final String topic;
    private final String clientId;
    private final String sourceId;

    public InputMessage(Object payload, String topic, String clientId, String sourceId) {
        this.payload = payload;
        this.topic = topic;
        this.clientId = clientId;
        this.sourceId = sourceId;
    }

    /** Returns the parsed message payload (typically a {@code Map<String,Object>} or raw String). */
    public Object getPayload() {
        return payload;
    }

    /** Returns the broker topic on which the message was received (inbound) or will be sent (outbound). */
    public String getTopic() {
        return topic;
    }

    /**
     * Returns the MQTT/broker client ID of the sending device.
     * Only populated for inbound mappings; {@code null} for outbound.
     */
    public String getClientId() {
        return clientId;
    }

    /**
     * Returns the Cumulocity internal device ID (source ID) of the originating device.
     * Only populated for outbound mappings; {@code null} for inbound.
     */
    public String getSourceId() {
        return sourceId;
    }
}
