package mqtt.mapping.model;

public enum ValidationError {
  Only_One_Multi_Level_Wildcard,
  Only_One_Single_Level_Wildcard,
  Multi_Level_Wildcard_Only_At_End,
  Only_One_Substitution_Defining_Device_Identifier_Can_Be_Used,
  One_Substitution_Defining_Device_Identifier_Must_Be_Used,
  TemplateTopic_Must_Match_The_SubscriptionTopic,
  TemplateTopic_Not_Unique,
  TemplateTopic_Must_Not_Be_Substring_Of_Other_TemplateTopic, 
  Target_Template_Must_Be_Valid_JSON, 
  Source_Template_Must_Be_Valid_JSON, 
  No_Multi_Level_Wildcard_Allowed_In_TemplateTopic,
  Device_Identifier_Must_Be_Selected, 
  TemplateTopic_And_TemplateTopicSample_Do_Not_Have_Same_Number_Of_Levels_In_Topic_Name,
  TemplateTopic_And_TemplateTopicSample_Do_Not_Have_Same_Structure_In_Topic_Name,
}
