/*
 * Copyright (c) 2022-2025 Cumulocity GmbH.
 *
 * SPDX-License-Identifier: Apache-2.0
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *       http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 *
 *  @authors Christof Strack, Stefan Witschel
 *
 */

package dynamic.mapper.model;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;

import jakarta.validation.constraints.NotNull;
import java.io.Serializable;
import java.util.Objects;

import io.swagger.v3.oas.annotations.media.Schema;

@Getter
@NoArgsConstructor
@AllArgsConstructor
@ToString(exclude = {})
@JsonIgnoreProperties(ignoreUnknown = true)
@Schema(description = "Mapping execution statistics and status information")
public class MappingStatus implements Serializable {

    /**
     * Pinned explicitly: without it the JVM derives the value from the field set and their
     * modifiers, so adding a counter — or merely making one {@code volatile} — silently breaks
     * Java deserialization of anything written by an earlier build. Status is persisted as JSON
     * (the {@code d11r_mapping} inventory fragment), so this only guards the {@code Serializable}
     * contract this class has always declared.
     */
    private static final long serialVersionUID = 1L;

    public static final String IDENT_UNSPECIFIED_MAPPING = "UNSPECIFIED";

    /**
     * Label shown for the catch-all status. Says what the row actually is — messages that no
     * mapping picked up — rather than naming the internal identifier; "Unspecified" told a user
     * nothing about what they were looking at. The identifier is unchanged, so this is purely
     * cosmetic and does not affect persisted status fragments.
     */
    public static final String UNSPECIFIED_DISPLAY_NAME = "Unmapped messages";

    /**
     * Creates the catch-all status that counts messages which matched <strong>no</strong>
     * mapping, plus errors raised before any mapping could be resolved (unparseable payload,
     * failed mapping resolution).
     *
     * <p>A factory, not a shared constant: these counters are per tenant, and a single static
     * instance handed to every tenant's status map would aggregate the counts of all subscribed
     * tenants into one object and report them to each of them.
     *
     * <p>Its {@code direction} is {@code null} because it spans both directions — consumers that
     * group by direction have to handle that explicitly.
     */
    public static MappingStatus createUnspecified() {
        return new MappingStatus(IDENT_UNSPECIFIED_MAPPING, IDENT_UNSPECIFIED_MAPPING,
                IDENT_UNSPECIFIED_MAPPING, null, "#", "#", 0, 0, 0, "");
    }

    /**
     * {@code true} for the catch-all status created by {@link #createUnspecified()}.
     *
     * <p>{@code @JsonIgnore}: this is a derived predicate, not state. Without it Jackson would
     * treat it as a bean property and add an {@code "unspecified"} field to the persisted
     * {@code d11r_mapping} fragment and to every REST payload carrying a status.
     */
    @JsonIgnore
    public boolean isUnspecified() {
        return IDENT_UNSPECIFIED_MAPPING.equals(identifier);
    }

    @Schema(requiredMode = Schema.RequiredMode.REQUIRED, description = "Unique identifier for the mapping generated by Cumulocity Core", example = "34573838974")
    @NotNull
    public String id;

    @Schema(requiredMode = Schema.RequiredMode.REQUIRED, description = "Display name of the mapping", example = "Temperature Sensor Data Mapping")
    @NotNull
    public String name;

    @Schema(requiredMode = Schema.RequiredMode.REQUIRED, description = "Generated identifier for the mapping", example = "l19zjk")
    @NotNull
    public String identifier;

    @Schema(requiredMode = Schema.RequiredMode.REQUIRED, description = "Direction of data flow for this mapping", implementation = Direction.class, example = "INBOUND")
    @NotNull
    public Direction direction;

    @Schema(requiredMode = Schema.RequiredMode.REQUIRED, description = "Topic pattern for incoming messages", example = "sensors/+/data")
    @NotNull
    public String mappingTopic;

    @Schema(requiredMode = Schema.RequiredMode.REQUIRED, description = "Topic pattern for outbound publishing", example = "device/+/temperature")
    @NotNull
    public String publishTopic;

    /**
     * Messages that reached this mapping's processing, counted once per mapping per message —
     * a message matching three mappings increments three counters. Lifetime total since the
     * service started or {@link #reset()} was called; not reset by (de)activation.
     *
     * <p>{@code volatile} for the same reason as {@link #currentFailureCount}: increments are
     * serialized by the instance monitor, but the status report reads it from another thread.
     */
    @Schema(requiredMode = Schema.RequiredMode.REQUIRED, description = "Total number of messages processed by this mapping. Counted per mapping, so one message matching several mappings increments each of them.", example = "1247")
    @NotNull
    public volatile long messagesReceived;

    /**
     * Lifetime number of failed messages. Unlike {@link #currentFailureCount} this is never
     * reset by a successful message, so it stays a usable error-rate indicator.
     */
    @Schema(requiredMode = Schema.RequiredMode.REQUIRED, description = "Total number of processing errors over the lifetime of this mapping. Never reset by successful processing.", example = "3")
    @NotNull
    public volatile long errors = 0;

    /**
     * Number of <strong>consecutive</strong> failures of this mapping: incremented on every
     * failed message, reset to 0 by the first message that completes without an error and on
     * (re)activation. Compared against {@code Mapping.maxFailureCount} to auto-deactivate a
     * persistently broken mapping — see {@code docs/feature/reliability.md}.
     *
     * <p>{@code volatile}: increments are serialized by {@link #incrementFailureCount()}'s
     * monitor, but the threshold check and the status report read the field from other threads,
     * where a plain non-volatile {@code long} read is neither guaranteed to be current nor
     * guaranteed to be non-torn.
     */
    @Schema(requiredMode = Schema.RequiredMode.REQUIRED, description = "Current consecutive failure count", example = "0")
    @NotNull
    public volatile long currentFailureCount = 0;

    /** Empty unless the mapping could not be loaded from the inventory; not a processing error. */
    @Schema(description = "Error message if the mapping failed to load; empty otherwise", example = "Invalid JSON template")
    @Setter
    public String loadingError;

    /**
     * Identity is the mapping {@code identifier} — the key every status map is keyed by, and
     * the only one that is always populated ({@code id}, the Cumulocity managed-object id, is
     * null for a status created before the mapping was persisted).
     */
    @Override
    public boolean equals(Object m) {
        return (m instanceof MappingStatus) && Objects.equals(identifier, ((MappingStatus) m).identifier);
    }

    @Override
    public int hashCode() {
        return Objects.hash(identifier);
    }

    /**
     * Clears every counter, including the failure streak — otherwise a mapping whose statistics
     * were just reset could still be one failure away from being auto-deactivated by a streak
     * it no longer reports.
     */
    public synchronized void reset() {
        messagesReceived = 0;
        errors = 0;
        currentFailureCount = 0;
        loadingError = "";
    }

    /**
     * A point-in-time copy, used for reporting: the live instance keeps being mutated by the
     * processing threads, so serializing it directly can emit a state that never existed (e.g.
     * an error counted but the message not yet counted).
     */
    public synchronized MappingStatus snapshot() {
        return new MappingStatus(id, name, identifier, direction, mappingTopic, publishTopic,
                messagesReceived, errors, currentFailureCount, loadingError);
    }

    /**
     * Counters below are mutated concurrently by multiple Camel processing threads
     * for the same mapping; synchronize on the instance to avoid lost updates.
     */
    public synchronized void incrementMessagesReceived() {
        messagesReceived++;
    }

    public synchronized void incrementErrors() {
        errors++;
    }

    public synchronized void incrementFailureCount() {
        currentFailureCount++;
    }

    public synchronized void resetFailureCount() {
        currentFailureCount = 0;
    }
}