/*
 * Copyright (c) 2022 Software AG, Darmstadt, Germany and/or Software AG USA Inc., Reston, VA, USA,
 * and/or its subsidiaries and/or its affiliates and/or their licensors.
 *
 * SPDX-License-Identifier: Apache-2.0
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * @authors Christof Strack, Stefan Witschel
 */

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: StaticCustomMeasurement.proto

package mqtt.mapping.processor.processor.fixed;

public final class StaticCustomMeasurementOuter {
  private StaticCustomMeasurementOuter() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface StaticCustomMeasurementOrBuilder extends
      // @@protoc_insertion_point(interface_extends:processor.protobuf.StaticCustomMeasurement)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int64 timestamp = 1;</code>
     * @return The timestamp.
     */
    long getTimestamp();

    /**
     * <code>float value = 2;</code>
     * @return The value.
     */
    float getValue();

    /**
     * <code>string unit = 3;</code>
     * @return The unit.
     */
    java.lang.String getUnit();
    /**
     * <code>string unit = 3;</code>
     * @return The bytes for unit.
     */
    com.google.protobuf.ByteString
        getUnitBytes();

    /**
     * <code>string externalIdType = 4;</code>
     * @return The externalIdType.
     */
    java.lang.String getExternalIdType();
    /**
     * <code>string externalIdType = 4;</code>
     * @return The bytes for externalIdType.
     */
    com.google.protobuf.ByteString
        getExternalIdTypeBytes();

    /**
     * <code>string externalId = 5;</code>
     * @return The externalId.
     */
    java.lang.String getExternalId();
    /**
     * <code>string externalId = 5;</code>
     * @return The bytes for externalId.
     */
    com.google.protobuf.ByteString
        getExternalIdBytes();

    /**
     * <code>string measurementType = 6;</code>
     * @return The measurementType.
     */
    java.lang.String getMeasurementType();
    /**
     * <code>string measurementType = 6;</code>
     * @return The bytes for measurementType.
     */
    com.google.protobuf.ByteString
        getMeasurementTypeBytes();
  }
  /**
   * Protobuf type {@code processor.protobuf.StaticCustomMeasurement}
   */
  public static final class StaticCustomMeasurement extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:processor.protobuf.StaticCustomMeasurement)
      StaticCustomMeasurementOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use StaticCustomMeasurement.newBuilder() to construct.
    private StaticCustomMeasurement(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private StaticCustomMeasurement() {
      unit_ = "";
      externalIdType_ = "";
      externalId_ = "";
      measurementType_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new StaticCustomMeasurement();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return mqtt.mapping.processor.processor.fixed.StaticCustomMeasurementOuter.internal_static_processor_protobuf_StaticCustomMeasurement_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return mqtt.mapping.processor.processor.fixed.StaticCustomMeasurementOuter.internal_static_processor_protobuf_StaticCustomMeasurement_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              mqtt.mapping.processor.processor.fixed.StaticCustomMeasurementOuter.StaticCustomMeasurement.class, mqtt.mapping.processor.processor.fixed.StaticCustomMeasurementOuter.StaticCustomMeasurement.Builder.class);
    }

    public static final int TIMESTAMP_FIELD_NUMBER = 1;
    private long timestamp_;
    /**
     * <code>int64 timestamp = 1;</code>
     * @return The timestamp.
     */
    @java.lang.Override
    public long getTimestamp() {
      return timestamp_;
    }

    public static final int VALUE_FIELD_NUMBER = 2;
    private float value_;
    /**
     * <code>float value = 2;</code>
     * @return The value.
     */
    @java.lang.Override
    public float getValue() {
      return value_;
    }

    public static final int UNIT_FIELD_NUMBER = 3;
    private volatile java.lang.Object unit_;
    /**
     * <code>string unit = 3;</code>
     * @return The unit.
     */
    @java.lang.Override
    public java.lang.String getUnit() {
      java.lang.Object ref = unit_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        unit_ = s;
        return s;
      }
    }
    /**
     * <code>string unit = 3;</code>
     * @return The bytes for unit.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getUnitBytes() {
      java.lang.Object ref = unit_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        unit_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int EXTERNALIDTYPE_FIELD_NUMBER = 4;
    private volatile java.lang.Object externalIdType_;
    /**
     * <code>string externalIdType = 4;</code>
     * @return The externalIdType.
     */
    @java.lang.Override
    public java.lang.String getExternalIdType() {
      java.lang.Object ref = externalIdType_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        externalIdType_ = s;
        return s;
      }
    }
    /**
     * <code>string externalIdType = 4;</code>
     * @return The bytes for externalIdType.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getExternalIdTypeBytes() {
      java.lang.Object ref = externalIdType_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        externalIdType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int EXTERNALID_FIELD_NUMBER = 5;
    private volatile java.lang.Object externalId_;
    /**
     * <code>string externalId = 5;</code>
     * @return The externalId.
     */
    @java.lang.Override
    public java.lang.String getExternalId() {
      java.lang.Object ref = externalId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        externalId_ = s;
        return s;
      }
    }
    /**
     * <code>string externalId = 5;</code>
     * @return The bytes for externalId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getExternalIdBytes() {
      java.lang.Object ref = externalId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        externalId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int MEASUREMENTTYPE_FIELD_NUMBER = 6;
    private volatile java.lang.Object measurementType_;
    /**
     * <code>string measurementType = 6;</code>
     * @return The measurementType.
     */
    @java.lang.Override
    public java.lang.String getMeasurementType() {
      java.lang.Object ref = measurementType_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        measurementType_ = s;
        return s;
      }
    }
    /**
     * <code>string measurementType = 6;</code>
     * @return The bytes for measurementType.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getMeasurementTypeBytes() {
      java.lang.Object ref = measurementType_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        measurementType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (timestamp_ != 0L) {
        output.writeInt64(1, timestamp_);
      }
      if (java.lang.Float.floatToRawIntBits(value_) != 0) {
        output.writeFloat(2, value_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(unit_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, unit_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(externalIdType_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, externalIdType_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(externalId_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, externalId_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(measurementType_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, measurementType_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (timestamp_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, timestamp_);
      }
      if (java.lang.Float.floatToRawIntBits(value_) != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(2, value_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(unit_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, unit_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(externalIdType_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, externalIdType_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(externalId_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, externalId_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(measurementType_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, measurementType_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof mqtt.mapping.processor.processor.fixed.StaticCustomMeasurementOuter.StaticCustomMeasurement)) {
        return super.equals(obj);
      }
      mqtt.mapping.processor.processor.fixed.StaticCustomMeasurementOuter.StaticCustomMeasurement other = (mqtt.mapping.processor.processor.fixed.StaticCustomMeasurementOuter.StaticCustomMeasurement) obj;

      if (getTimestamp()
          != other.getTimestamp()) return false;
      if (java.lang.Float.floatToIntBits(getValue())
          != java.lang.Float.floatToIntBits(
              other.getValue())) return false;
      if (!getUnit()
          .equals(other.getUnit())) return false;
      if (!getExternalIdType()
          .equals(other.getExternalIdType())) return false;
      if (!getExternalId()
          .equals(other.getExternalId())) return false;
      if (!getMeasurementType()
          .equals(other.getMeasurementType())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getTimestamp());
      hash = (37 * hash) + VALUE_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getValue());
      hash = (37 * hash) + UNIT_FIELD_NUMBER;
      hash = (53 * hash) + getUnit().hashCode();
      hash = (37 * hash) + EXTERNALIDTYPE_FIELD_NUMBER;
      hash = (53 * hash) + getExternalIdType().hashCode();
      hash = (37 * hash) + EXTERNALID_FIELD_NUMBER;
      hash = (53 * hash) + getExternalId().hashCode();
      hash = (37 * hash) + MEASUREMENTTYPE_FIELD_NUMBER;
      hash = (53 * hash) + getMeasurementType().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static mqtt.mapping.processor.processor.fixed.StaticCustomMeasurementOuter.StaticCustomMeasurement parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static mqtt.mapping.processor.processor.fixed.StaticCustomMeasurementOuter.StaticCustomMeasurement parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static mqtt.mapping.processor.processor.fixed.StaticCustomMeasurementOuter.StaticCustomMeasurement parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static mqtt.mapping.processor.processor.fixed.StaticCustomMeasurementOuter.StaticCustomMeasurement parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static mqtt.mapping.processor.processor.fixed.StaticCustomMeasurementOuter.StaticCustomMeasurement parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static mqtt.mapping.processor.processor.fixed.StaticCustomMeasurementOuter.StaticCustomMeasurement parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static mqtt.mapping.processor.processor.fixed.StaticCustomMeasurementOuter.StaticCustomMeasurement parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static mqtt.mapping.processor.processor.fixed.StaticCustomMeasurementOuter.StaticCustomMeasurement parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static mqtt.mapping.processor.processor.fixed.StaticCustomMeasurementOuter.StaticCustomMeasurement parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static mqtt.mapping.processor.processor.fixed.StaticCustomMeasurementOuter.StaticCustomMeasurement parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static mqtt.mapping.processor.processor.fixed.StaticCustomMeasurementOuter.StaticCustomMeasurement parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static mqtt.mapping.processor.processor.fixed.StaticCustomMeasurementOuter.StaticCustomMeasurement parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(mqtt.mapping.processor.processor.fixed.StaticCustomMeasurementOuter.StaticCustomMeasurement prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code processor.protobuf.StaticCustomMeasurement}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:processor.protobuf.StaticCustomMeasurement)
        mqtt.mapping.processor.processor.fixed.StaticCustomMeasurementOuter.StaticCustomMeasurementOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return mqtt.mapping.processor.processor.fixed.StaticCustomMeasurementOuter.internal_static_processor_protobuf_StaticCustomMeasurement_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return mqtt.mapping.processor.processor.fixed.StaticCustomMeasurementOuter.internal_static_processor_protobuf_StaticCustomMeasurement_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                mqtt.mapping.processor.processor.fixed.StaticCustomMeasurementOuter.StaticCustomMeasurement.class, mqtt.mapping.processor.processor.fixed.StaticCustomMeasurementOuter.StaticCustomMeasurement.Builder.class);
      }

      // Construct using mqtt.mapping.processor.processor.fixed.StaticCustomMeasurementOuter.StaticCustomMeasurement.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        timestamp_ = 0L;

        value_ = 0F;

        unit_ = "";

        externalIdType_ = "";

        externalId_ = "";

        measurementType_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return mqtt.mapping.processor.processor.fixed.StaticCustomMeasurementOuter.internal_static_processor_protobuf_StaticCustomMeasurement_descriptor;
      }

      @java.lang.Override
      public mqtt.mapping.processor.processor.fixed.StaticCustomMeasurementOuter.StaticCustomMeasurement getDefaultInstanceForType() {
        return mqtt.mapping.processor.processor.fixed.StaticCustomMeasurementOuter.StaticCustomMeasurement.getDefaultInstance();
      }

      @java.lang.Override
      public mqtt.mapping.processor.processor.fixed.StaticCustomMeasurementOuter.StaticCustomMeasurement build() {
        mqtt.mapping.processor.processor.fixed.StaticCustomMeasurementOuter.StaticCustomMeasurement result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public mqtt.mapping.processor.processor.fixed.StaticCustomMeasurementOuter.StaticCustomMeasurement buildPartial() {
        mqtt.mapping.processor.processor.fixed.StaticCustomMeasurementOuter.StaticCustomMeasurement result = new mqtt.mapping.processor.processor.fixed.StaticCustomMeasurementOuter.StaticCustomMeasurement(this);
        result.timestamp_ = timestamp_;
        result.value_ = value_;
        result.unit_ = unit_;
        result.externalIdType_ = externalIdType_;
        result.externalId_ = externalId_;
        result.measurementType_ = measurementType_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof mqtt.mapping.processor.processor.fixed.StaticCustomMeasurementOuter.StaticCustomMeasurement) {
          return mergeFrom((mqtt.mapping.processor.processor.fixed.StaticCustomMeasurementOuter.StaticCustomMeasurement)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(mqtt.mapping.processor.processor.fixed.StaticCustomMeasurementOuter.StaticCustomMeasurement other) {
        if (other == mqtt.mapping.processor.processor.fixed.StaticCustomMeasurementOuter.StaticCustomMeasurement.getDefaultInstance()) return this;
        if (other.getTimestamp() != 0L) {
          setTimestamp(other.getTimestamp());
        }
        if (other.getValue() != 0F) {
          setValue(other.getValue());
        }
        if (!other.getUnit().isEmpty()) {
          unit_ = other.unit_;
          onChanged();
        }
        if (!other.getExternalIdType().isEmpty()) {
          externalIdType_ = other.externalIdType_;
          onChanged();
        }
        if (!other.getExternalId().isEmpty()) {
          externalId_ = other.externalId_;
          onChanged();
        }
        if (!other.getMeasurementType().isEmpty()) {
          measurementType_ = other.measurementType_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                timestamp_ = input.readInt64();

                break;
              } // case 8
              case 21: {
                value_ = input.readFloat();

                break;
              } // case 21
              case 26: {
                unit_ = input.readStringRequireUtf8();

                break;
              } // case 26
              case 34: {
                externalIdType_ = input.readStringRequireUtf8();

                break;
              } // case 34
              case 42: {
                externalId_ = input.readStringRequireUtf8();

                break;
              } // case 42
              case 50: {
                measurementType_ = input.readStringRequireUtf8();

                break;
              } // case 50
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }

      private long timestamp_ ;
      /**
       * <code>int64 timestamp = 1;</code>
       * @return The timestamp.
       */
      @java.lang.Override
      public long getTimestamp() {
        return timestamp_;
      }
      /**
       * <code>int64 timestamp = 1;</code>
       * @param value The timestamp to set.
       * @return This builder for chaining.
       */
      public Builder setTimestamp(long value) {
        
        timestamp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 timestamp = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearTimestamp() {
        
        timestamp_ = 0L;
        onChanged();
        return this;
      }

      private float value_ ;
      /**
       * <code>float value = 2;</code>
       * @return The value.
       */
      @java.lang.Override
      public float getValue() {
        return value_;
      }
      /**
       * <code>float value = 2;</code>
       * @param value The value to set.
       * @return This builder for chaining.
       */
      public Builder setValue(float value) {
        
        value_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>float value = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearValue() {
        
        value_ = 0F;
        onChanged();
        return this;
      }

      private java.lang.Object unit_ = "";
      /**
       * <code>string unit = 3;</code>
       * @return The unit.
       */
      public java.lang.String getUnit() {
        java.lang.Object ref = unit_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          unit_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string unit = 3;</code>
       * @return The bytes for unit.
       */
      public com.google.protobuf.ByteString
          getUnitBytes() {
        java.lang.Object ref = unit_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          unit_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string unit = 3;</code>
       * @param value The unit to set.
       * @return This builder for chaining.
       */
      public Builder setUnit(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        unit_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string unit = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearUnit() {
        
        unit_ = getDefaultInstance().getUnit();
        onChanged();
        return this;
      }
      /**
       * <code>string unit = 3;</code>
       * @param value The bytes for unit to set.
       * @return This builder for chaining.
       */
      public Builder setUnitBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        unit_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object externalIdType_ = "";
      /**
       * <code>string externalIdType = 4;</code>
       * @return The externalIdType.
       */
      public java.lang.String getExternalIdType() {
        java.lang.Object ref = externalIdType_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          externalIdType_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string externalIdType = 4;</code>
       * @return The bytes for externalIdType.
       */
      public com.google.protobuf.ByteString
          getExternalIdTypeBytes() {
        java.lang.Object ref = externalIdType_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          externalIdType_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string externalIdType = 4;</code>
       * @param value The externalIdType to set.
       * @return This builder for chaining.
       */
      public Builder setExternalIdType(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        externalIdType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string externalIdType = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearExternalIdType() {
        
        externalIdType_ = getDefaultInstance().getExternalIdType();
        onChanged();
        return this;
      }
      /**
       * <code>string externalIdType = 4;</code>
       * @param value The bytes for externalIdType to set.
       * @return This builder for chaining.
       */
      public Builder setExternalIdTypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        externalIdType_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object externalId_ = "";
      /**
       * <code>string externalId = 5;</code>
       * @return The externalId.
       */
      public java.lang.String getExternalId() {
        java.lang.Object ref = externalId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          externalId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string externalId = 5;</code>
       * @return The bytes for externalId.
       */
      public com.google.protobuf.ByteString
          getExternalIdBytes() {
        java.lang.Object ref = externalId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          externalId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string externalId = 5;</code>
       * @param value The externalId to set.
       * @return This builder for chaining.
       */
      public Builder setExternalId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        externalId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string externalId = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearExternalId() {
        
        externalId_ = getDefaultInstance().getExternalId();
        onChanged();
        return this;
      }
      /**
       * <code>string externalId = 5;</code>
       * @param value The bytes for externalId to set.
       * @return This builder for chaining.
       */
      public Builder setExternalIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        externalId_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object measurementType_ = "";
      /**
       * <code>string measurementType = 6;</code>
       * @return The measurementType.
       */
      public java.lang.String getMeasurementType() {
        java.lang.Object ref = measurementType_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          measurementType_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string measurementType = 6;</code>
       * @return The bytes for measurementType.
       */
      public com.google.protobuf.ByteString
          getMeasurementTypeBytes() {
        java.lang.Object ref = measurementType_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          measurementType_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string measurementType = 6;</code>
       * @param value The measurementType to set.
       * @return This builder for chaining.
       */
      public Builder setMeasurementType(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        measurementType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string measurementType = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearMeasurementType() {
        
        measurementType_ = getDefaultInstance().getMeasurementType();
        onChanged();
        return this;
      }
      /**
       * <code>string measurementType = 6;</code>
       * @param value The bytes for measurementType to set.
       * @return This builder for chaining.
       */
      public Builder setMeasurementTypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        measurementType_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:processor.protobuf.StaticCustomMeasurement)
    }

    // @@protoc_insertion_point(class_scope:processor.protobuf.StaticCustomMeasurement)
    private static final mqtt.mapping.processor.processor.fixed.StaticCustomMeasurementOuter.StaticCustomMeasurement DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new mqtt.mapping.processor.processor.fixed.StaticCustomMeasurementOuter.StaticCustomMeasurement();
    }

    public static mqtt.mapping.processor.processor.fixed.StaticCustomMeasurementOuter.StaticCustomMeasurement getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<StaticCustomMeasurement>
        PARSER = new com.google.protobuf.AbstractParser<StaticCustomMeasurement>() {
      @java.lang.Override
      public StaticCustomMeasurement parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<StaticCustomMeasurement> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<StaticCustomMeasurement> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public mqtt.mapping.processor.processor.fixed.StaticCustomMeasurementOuter.StaticCustomMeasurement getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_processor_protobuf_StaticCustomMeasurement_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_processor_protobuf_StaticCustomMeasurement_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\035StaticCustomMeasurement.proto\022\022process" +
      "or.protobuf\"\216\001\n\027StaticCustomMeasurement\022" +
      "\021\n\ttimestamp\030\001 \001(\003\022\r\n\005value\030\002 \001(\002\022\014\n\004uni" +
      "t\030\003 \001(\t\022\026\n\016externalIdType\030\004 \001(\t\022\022\n\nexter" +
      "nalId\030\005 \001(\t\022\027\n\017measurementType\030\006 \001(\tBF\n&" +
      "mqtt.mapping.processor.processor.fixedB\034" +
      "StaticCustomMeasurementOuterb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_processor_protobuf_StaticCustomMeasurement_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_processor_protobuf_StaticCustomMeasurement_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_processor_protobuf_StaticCustomMeasurement_descriptor,
        new java.lang.String[] { "Timestamp", "Value", "Unit", "ExternalIdType", "ExternalId", "MeasurementType", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
