name: Check push requests

on:
  workflow_dispatch:
  push:
    # Sequence of patterns matched against refs/tags
    # tags:
    # - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
    branches:
      - '*'

permissions:
  contents: read

concurrency:
  group: typos-${{ github.ref }}
  cancel-in-progress: true

jobs:
  typos:
    name: Spell Check with Typos
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout Actions Repository
        uses: actions/checkout@v5

      - name: Check spelling
        uses: crate-ci/typos@v1.50.3
