# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Clean release zip

defaults:
  run:
    working-directory: backend
on:
  workflow_dispatch:


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Remove asset
      uses: flcdrg/remove-release-asset-action@v1
      id: remove
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        release_id: v1.3_beta
        aasset_name: mqtt-mapping-service-v1.3_beta.zip